#!/usr/bin/env python3
"""Generate builtins_matrix.test: every jq builtin x a fixed set of inputs.

Usage:
    python3 tests/jq_compat/corpus/gen_builtin_matrix.py          # jq on PATH
    JQ=/path/to/jq python3 tests/jq_compat/corpus/gen_builtin_matrix.py

The builtin list comes from `jq -n builtins` (jq 1.8.1). Each builtin is
called with `.` for every argument, and appears twice per input:

    f(.; .)                   compares outputs, exit code and the stderr error
    try f(.; .) catch .       compares the error value (message) as output

jq_diff runs the file in compact mode only (see the modes directive).
Regenerate after upgrading jq, and commit the result.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "builtins_matrix.test")
REQUIRED = "jq-1.8.1"

INPUTS = [
    "null",
    "true",
    "false",
    "0",
    "42",
    "-3",
    "-1.5",
    "3.75",
    '""',
    '"abc"',
    '"a,b"',
    '"2015-03-05T23:51:47Z"',
    '"héllo wörld 😀"',
    "[]",
    "[3,1,2]",
    '["b","a"]',
    "[[1,2],[3,4]]",
    '[{"a":2},{"a":1}]',
    "{}",
    '{"a":1,"b":[2,3]}',
]
FALSY = {"null", "false"}

# Not comparable between two different binaries, or not deterministic.
EXCLUDE = {
    "now/0": "wall clock",
    "get_jq_origin/0": "the running binary's directory (see cli.toml jq-origin-type)",
}

# Generators that never end with `.` as argument: wrapped in limit(8; ...).
INFINITE = {"repeat/1", "recurse/1", "recurse/2", "while/2"}


def skip_input(builtin, inp):
    # until(cond; update) with a falsy cond and update `.` loops forever
    # without output, so limit() can't stop it.
    if builtin == "until/2" and inp in FALSY:
        return True
    # jq's lgamma_r leaves the sign uninitialized at its poles (and for NaN
    # and infinities), so `0 | lgamma_r` differs from run to run.
    return builtin == "lgamma_r/0" and inp == "0"


def main():
    jq = os.environ.get("JQ", "jq")
    version = subprocess.run([jq, "--version"], capture_output=True, text=True).stdout.strip()
    if version != REQUIRED:
        sys.exit(f"{jq} is {version!r}, need {REQUIRED}")
    names = subprocess.run(
        [jq, "-nr", "builtins[]"], capture_output=True, text=True, check=True
    ).stdout.split()

    def key(b):
        name, arity = b.rsplit("/", 1)
        return (name, int(arity))

    lines = [
        "# Builtin x input matrix: every jq builtin called with `.` for each argument,",
        "# plain and inside try/catch, over a fixed set of inputs.",
        f"# Generated by gen_builtin_matrix.py from `{version} -n builtins`; don't edit by hand.",
        "#",
        "# Format: jq's .test format without expected output lines (program line, input",
        "# line, blank line). jq_diff compares jq and qj byte for byte.",
        "# jq_diff: modes=compact",
        "",
    ]
    excluded = []
    count = 0
    for b in sorted(set(names), key=key):
        if b in EXCLUDE:
            excluded.append(f"#   {b}: {EXCLUDE[b]}")
            continue
        name, arity = key(b)
        call = name if arity == 0 else f"{name}({'; '.join(['.'] * arity)})"
        if b in INFINITE:
            call = f"limit(8; {call})"
        lines.append(f"# {b}")
        for variant in (call, f"try {call} catch ."):
            for inp in INPUTS:
                if skip_input(b, inp):
                    continue
                lines += [variant, inp, ""]
                count += 1
    lines[7:7] = ["# Excluded builtins:"] + excluded + [""]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {count} cases")


main()
