//! jq 1.8.1 compiler conformance for `qj::jq::lang` (Track C1): bytecode and
//! compile errors, compared with `jq --debug-dump-disasm`.
//!
//! * `disasm_matches_recorded_jq`: fast. Replays `tests/jq_compile/disasm.jsonl`,
//!   which records what jq 1.8.1 prints for `jq --debug-dump-disasm -L modules --
//!   PROGRAM </dev/null` (the disassembly, or the compile errors and exit code 3) for
//!   every program of the upstream `.test` files (including `%%FAIL` blocks), qj's
//!   corpus (`tests/jq_compat/corpus/*.test`), Track P's corpus (`tests/jq_lang/`),
//!   this track's corpus (`tests/jq_compile/corpus.jsonl`: binding and scoping edge
//!   cases, named arguments, `$ENV`, modules), and generated deep programs. Our
//!   compiler must print exactly the same.
//! * `disasm_vs_live_jq` (ignored): the same against the jq binary; `QJ_BLESS=1`
//!   rewrites `disasm.jsonl`, `QJ_FILTER=text` selects programs.
//! * `adhoc` (ignored): `QJ_PROGRAM='...'` shows ours and jq's output.
//!
//!   ```text
//!   cargo test --release --test jq_compile -- --ignored --nocapture
//!   QJ_BLESS=1 cargo test --release --test jq_compile disasm_vs_live_jq -- --ignored --nocapture
//!   QJ_PROGRAM='def f: .; f' cargo test --release --test jq_compile adhoc -- --ignored --nocapture
//!   ```
//!
//! jq runs in `tests/jq_compat` with a fixed environment (see [`ENV`]) and
//! `-L modules`; paths under `tests/jq_compat` are recorded as `$ROOT`. Outputs
//! longer than [`MAX_RECORDED`] bytes are recorded as a hash.

use std::collections::{HashMap, HashSet};
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Duration;

use qj::jq::lang::bytecode::dump_disassembly;
use qj::jq::lang::linker::{JqAttrs, dirname, jq_realpath};
use qj::jq::lang::{CompileOptions, jq_compile_args};
use qj::jq::value::{Object, Str, Value};

const ROOT: &str = env!("CARGO_MANIFEST_DIR");

/// The environment jq runs with (sorted, as `Command` passes it).
const ENV: &[(&str, &str)] = &[("HOME", "/nonexistent-qj-home"), ("QJ_TEST", "1")];

/// Outputs longer than this are recorded as a hash (plus their length).
const MAX_RECORDED: usize = 256;

fn compat_dir() -> PathBuf {
    Path::new(ROOT).join("tests/jq_compat")
}

fn data_dir() -> PathBuf {
    Path::new(ROOT).join("tests/jq_compile")
}

fn jq_binary() -> PathBuf {
    if let Ok(jq) = std::env::var("JQ") {
        return PathBuf::from(jq);
    }
    let mise = PathBuf::from(std::env::var("HOME").unwrap_or_default())
        .join(".local/share/mise/installs/jq/1.8.1/jq");
    if mise.exists() {
        return mise;
    }
    PathBuf::from("jq")
}

// ---------------------------------------------------------------------------
// Programs
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct Program {
    origin: String,
    /// Raw bytes: a few programs are not valid UTF-8.
    src: Vec<u8>,
    /// jq options before the program: `--arg NAME VALUE` / `--argjson NAME JSON`.
    args: Vec<String>,
    /// Positional arguments after the program (`--args`).
    positional: Vec<String>,
    /// `$HOME`, relative to `tests/jq_compat` (default: [`ENV`]'s).
    home: Option<String>,
    /// Generated by [`generated_programs`] (recorded by origin only).
    generated: bool,
}

impl Program {
    fn new(origin: String, src: Vec<u8>) -> Program {
        Program {
            origin,
            src,
            args: Vec::new(),
            positional: Vec::new(),
            home: None,
            generated: false,
        }
    }

    /// Identity within the recording.
    fn key(&self) -> (Vec<u8>, Vec<String>, Vec<String>, Option<String>) {
        (
            self.src.clone(),
            self.args.clone(),
            self.positional.clone(),
            self.home.clone(),
        )
    }

    /// The environment jq runs with.
    fn env(&self) -> Vec<(String, String)> {
        ENV.iter()
            .map(|(k, v)| match (*k, &self.home) {
                ("HOME", Some(h)) => (k.to_string(), compat_root().join(h).display().to_string()),
                _ => (k.to_string(), v.to_string()),
            })
            .collect()
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn show(src: &[u8], n: usize) -> String {
    String::from_utf8_lossy(src).chars().take(n).collect()
}

fn strings(v: Option<&serde_json::Value>) -> Vec<String> {
    v.and_then(|v| v.as_array())
        .map(|a| a.iter().map(|s| s.as_str().unwrap().to_string()).collect())
        .unwrap_or_default()
}

/// A program from a JSON line: a string, or `{src|src_hex, origin?, args?,
/// positional?}`. `None` for Track P's generated entries (no source).
fn json_program(v: &serde_json::Value, default_origin: String) -> Option<Program> {
    match v {
        serde_json::Value::String(s) => Some(Program::new(default_origin, s.as_bytes().to_vec())),
        serde_json::Value::Object(o) => {
            let src = match (o.get("src"), o.get("src_hex")) {
                (Some(serde_json::Value::String(s)), _) => s.as_bytes().to_vec(),
                (_, Some(serde_json::Value::String(h))) => unhex(h),
                _ => return None,
            };
            let mut p = Program::new(
                o.get("origin")
                    .and_then(|v| v.as_str())
                    .map_or(default_origin, str::to_string),
                src,
            );
            p.args = strings(o.get("args"));
            p.positional = strings(o.get("positional"));
            p.home = o.get("home").and_then(|v| v.as_str()).map(str::to_string);
            Some(p)
        }
        _ => None,
    }
}

fn skipline(line: &str) -> bool {
    let rest = line.trim_start_matches([' ', '\t']);
    rest.is_empty() || rest.starts_with('#')
}

/// The programs of a jq `.test` file (jq_test.c's format).
fn test_file_programs(name: &str, content: &str, out: &mut Vec<Program>) {
    let lines: Vec<&str> = content.split('\n').collect();
    let mut i = 0;
    let mut must_fail = false;
    while i < lines.len() {
        let line = lines[i];
        let lineno = i + 1;
        i += 1;
        if skipline(line) {
            continue;
        }
        if line == "%%FAIL" || line == "%%FAIL IGNORE MSG" {
            must_fail = true;
            continue;
        }
        let origin = format!("{name}:{lineno}{}", if must_fail { " %%FAIL" } else { "" });
        out.push(Program::new(origin, line.as_bytes().to_vec()));
        if !must_fail {
            i += 1; // the input line
        }
        while i < lines.len() && !skipline(lines[i]) {
            i += 1;
        }
        must_fail = false;
    }
}

fn jsonl_programs(path: &Path, out: &mut Vec<Program>) {
    let name = path.file_name().unwrap().to_string_lossy().to_string();
    let content = std::fs::read_to_string(path).unwrap();
    for (n, line) in content.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let v: serde_json::Value = serde_json::from_str(line)
            .unwrap_or_else(|e| panic!("{}:{}: {e}", path.display(), n + 1));
        if let Some(p) = json_program(&v, format!("{name}:{}", n + 1)) {
            out.push(p);
        }
    }
}

/// Deep and long programs, around jq's limits (bison's 10000-state stack, the
/// 65535-unit function length) and past the depths where recursion would overflow.
fn generated_programs() -> Vec<(String, Vec<u8>)> {
    let mut out: Vec<(String, String)> = Vec::new();
    // Track P's: jq folds these while parsing, so they compile at any length.
    out.push((
        "chain-plus[100000]".into(),
        format!("1{}", "+1".repeat(100_000)),
    ));
    out.push((
        "chain-comma[100000]".into(),
        format!("[1{}]", ",1".repeat(100_000)),
    ));
    for n in [3400usize, 5000] {
        let pairs: Vec<String> = (0..n).map(|i| format!("a{i}:1")).collect();
        out.push((
            format!("object-pairs[{n}]"),
            format!("{{{}}}", pairs.join(",")),
        ));
    }
    for n in [4999usize, 9996] {
        out.push((format!("deep-neg[{n}]"), "-".repeat(n) + "1"));
    }
    for n in [9998usize, 10001] {
        out.push((format!("deep[{n}]"), "[".repeat(n) + &"]".repeat(n)));
    }
    out.push((
        "deep-paren-plus[4999]".into(),
        "(1+".repeat(4999) + "1" + &")".repeat(4999),
    ));
    out.push((
        "deep-interp[3333]".into(),
        "\"\\(".repeat(3333) + &")\"".repeat(3333),
    ));
    // Non-constant arithmetic nests one lambda per operator.
    for n in [3000usize, 10923, 20000] {
        out.push((format!("dotplus[{n}]"), vec!["."; n].join(" + ")));
    }
    for n in [21844usize, 21845, 100_000] {
        out.push((format!("field[{n}]"), ".a".repeat(n)));
    }
    out.push((
        "deepcall[1000]".into(),
        "def f(g): g; ".to_string() + &"f(".repeat(1000) + "." + &")".repeat(1000),
    ));
    for n in [1000usize, 3000] {
        let defs: String = (0..n).map(|i| format!("def f{i}: ")).collect();
        let uses: String = (0..n).rev().map(|i| format!("; f{i}")).collect();
        out.push((format!("deepdef[{n}]"), defs + "." + &uses));
    }
    let chain: String = (1..4000)
        .map(|i| format!("def f{i}: f{}; ", i - 1))
        .collect();
    out.push(("manydefs[4000]".into(), format!("def f0: 1; {chain}f3999")));
    let vars: String = (0..1000).map(|i| format!("1 as $x{i} | ")).collect();
    out.push(("manyvars[1000]".into(), vars + "[$x0, $x999]"));
    out.push(("deeptry[4990]".into(), "try ".repeat(4990) + "1"));
    out.push((
        "deepcollect[3000]".into(),
        "[.[] | ".repeat(3000) + "." + &"]".repeat(3000),
    ));
    let flat: Vec<String> = (0..6554).map(|i| format!("(1 as $x{i} | $x{i})")).collect();
    out.push(("manyvarsflat[6554]".into(), format!("[{}]", flat.join(","))));
    out.into_iter()
        .map(|(n, s)| (format!("gen:{n}"), s.into_bytes()))
        .collect()
}

fn collect_programs() -> Vec<Program> {
    let mut all = Vec::new();
    for dir in [compat_dir(), compat_dir().join("corpus")] {
        let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().path())
            .filter(|p| p.extension().is_some_and(|e| e == "test"))
            .collect();
        files.sort();
        for f in files {
            let name = f.strip_prefix(compat_dir()).unwrap().display().to_string();
            let content = std::fs::read_to_string(&f).unwrap();
            test_file_programs(&name, &content, &mut all);
        }
    }
    for f in ["corpus.jsonl", "cases.jsonl"] {
        jsonl_programs(&Path::new(ROOT).join("tests/jq_lang").join(f), &mut all);
    }
    jsonl_programs(&data_dir().join("corpus.jsonl"), &mut all);
    for (origin, src) in generated_programs() {
        let mut p = Program::new(origin, src);
        p.generated = true;
        all.push(p);
    }
    // Deduplicate; jq's CLI reads the program as a C string, so skip ones with NUL.
    let mut seen = HashSet::new();
    all.retain(|p| !p.src.contains(&0) && seen.insert(p.key()));
    all
}

// ---------------------------------------------------------------------------
// Running jq and ours
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq, Eq)]
struct Outcome {
    exit: i32,
    stdout: String,
    stderr: String,
}

/// `realpath(tests/jq_compat)`.
fn compat_root() -> PathBuf {
    let root = jq_realpath(Value::from(compat_dir().to_str().unwrap()));
    PathBuf::from(root.as_str().unwrap())
}

fn normalize(s: &str) -> String {
    s.replace(compat_root().to_str().unwrap(), "$ROOT")
}

/// What main.c passes to `jq_compile_args` for `p`'s arguments (without
/// `JQ_BUILD_CONFIGURATION`), and the attributes it sets.
fn options(p: &Program) -> CompileOptions {
    let mut named = Object::new();
    let mut i = 0;
    while i + 3 <= p.args.len() {
        let (opt, name, text) = (&p.args[i], &p.args[i + 1], &p.args[i + 2]);
        // First definition wins.
        if !named.contains_key(name) {
            let v = match opt.as_str() {
                "--arg" => Value::from(text.as_str()),
                "--argjson" => qj::jq::value::parse::parse(text).expect("--argjson value"),
                o => panic!("unsupported option {o}"),
            };
            named.insert(Str::from(name.as_str()), v);
        }
        i += 3;
    }
    let mut a = Object::new();
    let positional: Vec<Value> = p
        .positional
        .iter()
        .map(|s| Value::from(s.as_str()))
        .collect();
    a.insert(Str::from("positional"), Value::from(positional));
    a.insert(Str::from("named"), Value::Object(named.clone()));
    let mut args = named;
    args.insert(Str::from("ARGS"), Value::Object(a));
    let mut env = Object::new();
    let penv = p.env();
    for (k, v) in &penv {
        env.insert(Str::from(k.as_str()), Value::from(v.as_str()));
    }
    let modules = jq_realpath(Value::from(compat_dir().join("modules").to_str().unwrap()));
    CompileOptions {
        args,
        env: Some(Value::Object(env)),
        attrs: JqAttrs {
            // main.c realpaths each -L directory
            lib_dirs: Value::from(vec![modules]),
            jq_origin: Value::from(dirname(jq_binary().to_str().unwrap()).as_str()),
            prog_origin: jq_realpath(Value::from(compat_dir().to_str().unwrap())),
            home: Some(penv[0].1.clone()),
        },
    }
}

fn ours(p: &Program) -> Outcome {
    match jq_compile_args(&p.src, &options(p)) {
        Ok(bc) => Outcome {
            exit: 0,
            stdout: normalize(&format!("{}\n", dump_disassembly(0, &bc))),
            stderr: String::new(),
        },
        Err(e) => Outcome {
            exit: 3,
            stdout: String::new(),
            stderr: normalize(&e.render()),
        },
    }
}

/// jq's outcome, or `None` if it crashed or timed out.
fn live_jq(jq: &Path, p: &Program) -> Option<Outcome> {
    use std::os::unix::ffi::OsStrExt;
    let mut cmd = Command::new(jq);
    cmd.args(["--debug-dump-disasm", "-L", "modules"])
        .args(&p.args);
    if !p.positional.is_empty() {
        cmd.arg("--args");
    }
    cmd.arg("--")
        .arg(std::ffi::OsStr::from_bytes(&p.src))
        .args(&p.positional)
        .current_dir(compat_dir())
        .env_clear()
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    for (k, v) in p.env() {
        cmd.env(k, v);
    }
    let child = cmd.spawn().ok()?;
    let out = wait_with_timeout(child, Duration::from_secs(60))?;
    let exit = out.status.code()?;
    Some(Outcome {
        exit,
        stdout: normalize(&String::from_utf8_lossy(&out.stdout)),
        stderr: normalize(&String::from_utf8_lossy(&out.stderr)),
    })
}

fn wait_with_timeout(child: std::process::Child, t: Duration) -> Option<std::process::Output> {
    let (tx, rx) = std::sync::mpsc::channel();
    let id = child.id();
    std::thread::spawn(move || {
        let _ = tx.send(child.wait_with_output());
    });
    match rx.recv_timeout(t) {
        Ok(r) => r.ok(),
        Err(_) => {
            // SAFETY: plain kill(2) of our own child.
            unsafe { libc::kill(id as i32, libc::SIGKILL) };
            None
        }
    }
}

// ---------------------------------------------------------------------------
// Recorded expectations
// ---------------------------------------------------------------------------

fn fnv64(s: &str) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in s.as_bytes() {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

fn record_text(s: &str) -> serde_json::Value {
    if s.len() <= MAX_RECORDED {
        serde_json::Value::String(s.to_string())
    } else {
        serde_json::json!({ "len": s.len(), "fnv64": format!("{:016x}", fnv64(s)) })
    }
}

fn matches_record(actual: &str, rec: &serde_json::Value) -> bool {
    match rec {
        serde_json::Value::String(s) => s == actual,
        serde_json::Value::Object(o) => {
            o["len"].as_u64() == Some(actual.len() as u64)
                && o["fnv64"].as_str() == Some(format!("{:016x}", fnv64(actual)).as_str())
        }
        _ => false,
    }
}

fn record_of(p: &Program, out: &Outcome) -> serde_json::Value {
    let mut rec = serde_json::json!({
        "origin": p.origin,
        "exit": out.exit,
        "stdout": record_text(&out.stdout),
        "stderr": record_text(&out.stderr),
    });
    if !p.generated {
        match std::str::from_utf8(&p.src) {
            Ok(s) => rec["src"] = serde_json::Value::String(s.to_string()),
            Err(_) => rec["src_hex"] = serde_json::Value::String(hex(&p.src)),
        }
    }
    if !p.args.is_empty() {
        rec["args"] = serde_json::json!(p.args);
    }
    if !p.positional.is_empty() {
        rec["positional"] = serde_json::json!(p.positional);
    }
    if let Some(h) = &p.home {
        rec["home"] = serde_json::json!(h);
    }
    rec
}

fn first_difference(a: &str, b: &str) -> String {
    let al: Vec<&str> = a.lines().collect();
    let bl: Vec<&str> = b.lines().collect();
    for i in 0..al.len().max(bl.len()) {
        let x = al.get(i).copied().unwrap_or("<eof>");
        let y = bl.get(i).copied().unwrap_or("<eof>");
        if x != y {
            return format!("line {}: jq {:?} vs ours {:?}", i + 1, x, y);
        }
    }
    "(identical lines)".into()
}

/// Runs `f` on a thread with a big stack: the deepest programs nest as deeply as
/// jq's parser allows, and this test checks the output, not our stack usage.
fn on_big_stack<T: Send + 'static>(f: impl FnOnce() -> T + Send + 'static) -> T {
    std::thread::Builder::new()
        .stack_size(256 << 20)
        .spawn(f)
        .unwrap()
        .join()
        .unwrap()
}

#[test]
fn disasm_matches_recorded_jq() {
    on_big_stack(|| {
        let content = std::fs::read_to_string(data_dir().join("disasm.jsonl"))
            .expect("tests/jq_compile/disasm.jsonl");
        let generated: HashMap<String, Vec<u8>> = generated_programs().into_iter().collect();
        let mut failures = Vec::new();
        let mut timings = Vec::new();
        let mut n = 0;
        for line in content.lines() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let rec: serde_json::Value = serde_json::from_str(line).unwrap();
            let origin = rec["origin"].as_str().unwrap_or("").to_string();
            let p = match json_program(&rec, origin.clone()) {
                Some(p) => p,
                None => match generated.get(&origin) {
                    Some(src) => Program::new(origin.clone(), src.clone()),
                    None => panic!("recorded program {origin} is not generated any more"),
                },
            };
            n += 1;
            let t0 = std::time::Instant::now();
            let got = ours(&p);
            timings.push((t0.elapsed(), origin.clone()));
            let exit = rec["exit"].as_i64().unwrap() as i32;
            let ok = got.exit == exit
                && matches_record(&got.stdout, &rec["stdout"])
                && matches_record(&got.stderr, &rec["stderr"]);
            if !ok {
                let detail = match (&rec["stdout"], &rec["stderr"]) {
                    (serde_json::Value::String(o), serde_json::Value::String(e)) => {
                        first_difference(
                            &format!("{o}{e}"),
                            &format!("{}{}", got.stdout, got.stderr),
                        )
                    }
                    _ => "(recorded as a hash; run disasm_vs_live_jq)".into(),
                };
                failures.push(format!(
                    "{origin}: {:?}\n  exit: jq {exit} ours {}\n  {detail}",
                    show(&p.src, 120),
                    got.exit
                ));
            }
        }
        assert!(n > 3000, "only {n} recorded programs");
        if std::env::var("QJ_TIMING").is_ok() {
            timings.sort();
            let total: Duration = timings.iter().map(|t| t.0).sum();
            eprintln!("total {total:?}");
            for (t, o) in timings.iter().rev().take(25) {
                eprintln!("{t:?} {o}");
            }
        }
        if !failures.is_empty() {
            panic!(
                "{} of {} programs differ from jq:\n{}",
                failures.len(),
                n,
                failures
                    .iter()
                    .take(40)
                    .cloned()
                    .collect::<Vec<_>>()
                    .join("\n")
            );
        }
    });
}

#[test]
#[ignore]
fn disasm_vs_live_jq() {
    on_big_stack(disasm_vs_live_jq_impl);
}

fn disasm_vs_live_jq_impl() {
    let jq = jq_binary();
    match Command::new(&jq).arg("--version").output() {
        Ok(o) if String::from_utf8_lossy(&o.stdout).trim() == "jq-1.8.1" => {}
        _ => {
            eprintln!("disasm_vs_live_jq: skipped, need jq 1.8.1 (set JQ)");
            return;
        }
    }
    let filter = std::env::var("QJ_FILTER").ok();
    let programs: Vec<Program> = collect_programs()
        .into_iter()
        .filter(|p| {
            filter.as_ref().is_none_or(|f| {
                String::from_utf8_lossy(&p.src).contains(f.as_str())
                    || p.origin.contains(f.as_str())
            })
        })
        .collect();

    // Run jq in parallel.
    let jobs = std::thread::available_parallelism().map_or(4, |n| n.get());
    let next = std::sync::atomic::AtomicUsize::new(0);
    let mut jq_results: Vec<Option<Outcome>> = vec![None; programs.len()];
    std::thread::scope(|s| {
        let handles: Vec<_> = (0..jobs)
            .map(|_| {
                s.spawn(|| {
                    let mut done = Vec::new();
                    loop {
                        let i = next.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                        if i >= programs.len() {
                            break;
                        }
                        done.push((i, live_jq(&jq, &programs[i])));
                    }
                    done
                })
            })
            .collect();
        for h in handles {
            for (i, r) in h.join().unwrap() {
                jq_results[i] = r;
            }
        }
    });

    let mut pass = 0;
    let mut crashed = Vec::new();
    let mut fails = Vec::new();
    let mut records = Vec::new();
    let (mut ok_disasm, mut tot_disasm, mut ok_err, mut tot_err) = (0, 0, 0, 0);
    for (p, jq_out) in programs.iter().zip(&jq_results) {
        let Some(jq_out) = jq_out else {
            crashed.push(p.origin.clone());
            continue;
        };
        let got = ours(p);
        let same = &got == jq_out;
        if jq_out.exit == 0 {
            tot_disasm += 1;
            ok_disasm += same as usize;
        } else {
            tot_err += 1;
            ok_err += same as usize;
        }
        if same {
            pass += 1;
        } else {
            fails.push((p, jq_out.clone(), got));
        }
        records.push(record_of(p, jq_out));
    }
    let report_path = Path::new(env!("CARGO_TARGET_TMPDIR")).join("jq_compile_report.txt");
    let mut report = std::fs::File::create(&report_path).unwrap();
    for (p, jq_out, got) in &fails {
        let _ = writeln!(
            report,
            "=== {} {:?} {:?} {:?}\n--- jq (exit {})\n{}{}--- ours (exit {})\n{}{}",
            p.origin,
            show(&p.src, 300),
            p.args,
            p.positional,
            jq_out.exit,
            jq_out.stdout,
            jq_out.stderr,
            got.exit,
            got.stdout,
            got.stderr
        );
    }
    eprintln!(
        "disasm_vs_live_jq: {pass}/{} identical; disassembly {ok_disasm}/{tot_disasm}, \
         compile errors {ok_err}/{tot_err}; {} skipped (jq crashed or timed out: {:?}); report: {}",
        programs.len() - crashed.len(),
        crashed.len(),
        crashed,
        report_path.display()
    );
    for (p, jq_out, got) in fails.iter().take(15) {
        eprintln!(
            "  {} {:?}: {}",
            p.origin,
            show(&p.src, 80),
            first_difference(
                &format!("{}{}", jq_out.stdout, jq_out.stderr),
                &format!("{}{}", got.stdout, got.stderr)
            )
        );
    }
    if std::env::var("QJ_BLESS").is_ok_and(|v| v == "1") && filter.is_none() {
        let path = data_dir().join("disasm.jsonl");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(
            f,
            "# jq 1.8.1 --debug-dump-disasm -L modules [ARGS] -- PROGRAM </dev/null, run in tests/jq_compat.\n\
             # Generated by `QJ_BLESS=1 cargo test --release --test jq_compile disasm_vs_live_jq -- --ignored`."
        )
        .unwrap();
        for r in &records {
            writeln!(f, "{}", serde_json::to_string(r).unwrap()).unwrap();
        }
        eprintln!("wrote {}", path.display());
    }
    assert!(fails.is_empty(), "{} programs differ from jq", fails.len());
}

#[test]
#[ignore]
fn adhoc() {
    on_big_stack(|| {
        let Ok(src) = std::env::var("QJ_PROGRAM") else {
            return;
        };
        let p = Program::new("adhoc".into(), src.into_bytes());
        let got = ours(&p);
        println!("--- ours (exit {})\n{}{}", got.exit, got.stdout, got.stderr);
        if let Some(j) = live_jq(&jq_binary(), &p) {
            println!("--- jq (exit {})\n{}{}", j.exit, j.stdout, j.stderr);
            println!("--- {}", if j == got { "SAME" } else { "DIFFERENT" });
        }
    });
}

/// Rough compile-time check (not a benchmark): `cargo test --release --test
/// jq_compile compile_speed -- --ignored --nocapture`.
#[test]
#[ignore]
fn compile_speed() {
    use std::time::Instant;
    let opts = CompileOptions::new(".");
    let t = Instant::now();
    jq_compile_args(b".", &opts).unwrap();
    eprintln!("first compile in the process: {:?}", t.elapsed());
    for src in [
        ".",
        ".a",
        ".a + 1",
        "map(.+1)",
        "select(.a == 1) | {b}",
        "[paths]",
        "sub(\"a\"; \"b\")",
        "to_entries | map(select(.value > 1)) | from_entries",
        "limit(3; .[]) | tostring | ascii_downcase",
    ] {
        let n = 2000;
        let t = Instant::now();
        for _ in 0..n {
            jq_compile_args(src.as_bytes(), &opts).unwrap();
        }
        eprintln!("{:>10.1?} per compile: {src}", t.elapsed() / n);
    }
}
