#!/usr/bin/env python3
"""Generate src/jq/lang/parser_tables.rs from jq 1.8.1's bison output (src/parser.c).

jq ships the LALR(1) tables that bison 3.8.2 generated from parser.y. We port them
verbatim so the Rust parser accepts, rejects, recovers from errors, and words its
"syntax error, unexpected X, expecting Y" messages exactly like jq.

Usage:
    python3 src/jq/lang/gen_parser_tables.py [path/to/jq-1.8.1/src/parser.c]

Default input: target/jq-src/jq-1.8.1/src/parser.c
(run `bash tests/jq_compat/fetch_jq_source.sh` first).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DEFAULT_SRC = os.path.join(ROOT, "target", "jq-src", "jq-1.8.1", "src", "parser.c")
OUT = os.path.join(ROOT, "src", "jq", "lang", "parser_tables.rs")


def int_array(src, name):
    m = re.search(r"static const (\w+) %s\[\] =\s*\{([^}]*)\};" % re.escape(name), src)
    if not m:
        sys.exit("table %s not found" % name)
    return m.group(1), [int(x) for x in m.group(2).replace("\n", " ").split(",") if x.strip()]


def define(src, name):
    m = re.search(r"#define %s\s+\(?(-?\d+)\)?" % re.escape(name), src)
    if not m:
        sys.exit("define %s not found" % name)
    return int(m.group(1))


def yytnamerr(s):
    """Port of bison's yytnamerr: strip double quotes unless the name needs them."""
    if s.startswith('"'):
        out = []
        i = 1
        while True:
            c = s[i]
            if c in ("'", ","):
                return s
            if c == "\\":
                i += 1
                if s[i] != "\\":
                    return s
                out.append("\\")
            elif c == '"':
                return "".join(out)
            else:
                out.append(c)
            i += 1
    return s


def c_string_list(body):
    names = []
    for m in re.finditer(r'"((?:[^"\\]|\\.)*)"|YY_NULLPTR', body):
        if m.group(0) == "YY_NULLPTR":
            break
        raw = m.group(1)
        # undo C escaping (only \" and \\ occur)
        names.append(raw.replace('\\"', '"').replace("\\\\", "\\"))
    return names


def rust_array(name, ctype, values, per_line=12):
    rtype = {
        "yytype_int8": "i8",
        "yytype_uint8": "u8",
        "yytype_int16": "i16",
        "yytype_uint16": "u16",
    }[ctype]
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("    " + " ".join("%d," % v for v in values[i:i + per_line]))
    return "pub(crate) static %s: [%s; %d] = [\n%s\n];\n" % (name, rtype, len(values), "\n".join(lines))


def main():
    src_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    with open(src_path, encoding="utf-8") as f:
        src = f.read()
    if '#define YYBISON_VERSION "3.8.2"' not in src:
        sys.exit("expected a bison 3.8.2 parser.c")

    consts = {n: define(src, n) for n in
              ["YYFINAL", "YYLAST", "YYNTOKENS", "YYNNTS", "YYNRULES", "YYNSTATES",
               "YYPACT_NINF", "YYTABLE_NINF"]}
    tables = {n: int_array(src, n) for n in
              ["yypact", "yydefact", "yypgoto", "yydefgoto", "yytable", "yycheck",
               "yystos", "yyr1", "yyr2"]}

    m = re.search(r"static const char \*const yytname\[\] =\s*\{(.*?)\};", src, re.S)
    names = c_string_list(m.group(1))
    assert len(names) == consts["YYNTOKENS"] + consts["YYNNTS"], len(names)

    # Symbol kinds, e.g. `YYSYMBOL_IDENT = 4,  /* IDENT */`
    kinds = re.findall(r"^\s*YYSYMBOL_(\w+) = (-?\d+),?\s*/\*\s*(.*?)\s*\*/", src, re.M)
    # Rule descriptions from the action switch: `case 13: /* Query: Query '|' Query  */`
    rules = {int(n): d.strip() for n, d in re.findall(r"^  case (\d+): /\* (.*?)\s*\*/", src, re.M)}

    out = []
    out.append("// @generated by src/jq/lang/gen_parser_tables.py from jq 1.8.1's src/parser.c\n")
    out.append("// (bison 3.8.2 output for src/parser.y). Do not edit by hand.\n")
    out.append("//\n// These are the LALR(1) tables of jq's grammar; see parser.rs for the ported\n")
    out.append("// yacc.c skeleton that drives them. Derived from jq (MIT, see LICENSE-jq).\n\n")
    out.append("#![allow(dead_code)]\n\n")
    for n in ["YYFINAL", "YYLAST", "YYNTOKENS", "YYNNTS", "YYNRULES", "YYNSTATES"]:
        out.append("pub(crate) const %s: i32 = %d;\n" % (n, consts[n]))
    out.append("pub(crate) const YYPACT_NINF: i16 = %d;\n" % consts["YYPACT_NINF"])
    out.append("pub(crate) const YYTABLE_NINF: i16 = %d;\n\n" % consts["YYTABLE_NINF"])

    out.append("/// Symbol kinds (`yysymbol_kind_t`): terminals `0..YYNTOKENS`, then nonterminals.\n")
    out.append("pub(crate) mod sym {\n")
    for name, val, comment in kinds:
        if int(val) < 0:
            continue
        rname = name
        if re.fullmatch(r"\d+_", name):
            # character literal tokens, e.g. YYSYMBOL_48_ /* '|' */
            ch = comment.strip("'")
            char_names = {"|": "PIPE", ",": "COMMA", "=": "ASSIGN", "<": "LESS", ">": "GREATER",
                          "+": "PLUS", "-": "MINUS", "*": "STAR", "/": "SLASH", "%": "PERCENT",
                          "?": "QUESTION", ".": "DOT", "[": "LBRACKET", ";": "SEMICOLON",
                          ":": "COLON", "(": "LPAREN", ")": "RPAREN", "]": "RBRACKET",
                          "{": "LBRACE", "}": "RBRACE", "$": "DOLLAR"}
            rname = char_names[ch]
        if int(val) >= consts["YYNTOKENS"]:
            # nonterminals; prefixed because some share a name with a token (MODULE, ...)
            rname = "NT_" + rname
        out.append("    pub const %s: u8 = %s; // %s\n" % (rname.upper(), val, comment))
    out.append("}\n\n")

    out.append("/// `yytname` after bison's `yytnamerr` (the names used in syntax error messages).\n")
    out.append("pub(crate) static YYTNAME: [&str; %d] = [\n" % len(names))
    for n in names:
        out.append("    %s,\n" % rust_str(yytnamerr(n)))
    out.append("];\n\n")

    for n in ["yypact", "yydefact", "yypgoto", "yydefgoto", "yytable", "yycheck", "yystos", "yyr1", "yyr2"]:
        ctype, vals = tables[n]
        out.append(rust_array(n.upper(), ctype, vals))
        out.append("\n")

    out.append("/// Rule descriptions (index = bison rule number), for debugging and tests.\n")
    nrules = consts["YYNRULES"]
    out.append("pub(crate) static RULE_NAMES: [&str; %d] = [\n" % (nrules + 1))
    out.append("    \"\",\n    \"$accept: TopLevel \\\"end of file\\\"\",\n")
    for i in range(2, nrules + 1):
        out.append("    %s,\n" % rust_str(rules[i]))
    out.append("];\n")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(out))
    print("wrote", OUT)


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
