//! Port of jq 1.8.1's `parser.y`: the grammar's LALR(1) tables (generated by bison
//! 3.8.2, extracted into `parser_tables.rs`), the `yacc.c` skeleton that drives them,
//! and the semantic actions, which build an [`ast::Program`] instead of bytecode.
//!
//! Using bison's own tables and skeleton makes the parser agree with jq exactly on:
//! which programs are accepted; operator precedence and associativity (resolved into
//! the tables from `%precedence`/`%left`/`%right`/`%nonassoc`); the wording of syntax
//! errors, including bison's "expecting ..." lists (which LALR default reductions
//! make quirky, e.g. `@` reports "expecting end of file"); error recovery through the
//! grammar's `error` rules, which decides how many errors are reported and what they
//! say; and the 10000-state stack limit ("memory exhausted").
//!
//! Errors are reported in the order jq reports them. Checks that jq performs in its
//! actions but that need constant folding (object keys like `{(0): 1}`, module
//! metadata) are delegated to [`ParseHooks`], called at the same point of the parse.

use super::ast::*;
use super::lexer::{Lexer, Token};
use super::parser_tables::*;

/// A parse-time error, in the order jq reports it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ParseError {
    /// The message as passed to `yyerror`, without the `jq: error: ` prefix, e.g.
    /// `syntax error, unexpected IDENT, expecting end of file`.
    pub message: String,
    /// Where jq points: the lookahead token for syntax errors, the rule's `@$` or `@N`
    /// for errors raised by actions.
    pub loc: Loc,
}

impl ParseError {
    /// The error exactly as jq prints it (without the trailing newline): `jq: error:
    /// <message> at <file>, line N, column M:` plus the source line and carets.
    pub fn render(&self, locfile: &super::locfile::LocFile) -> String {
        locfile.locate(self.loc, &format!("jq: error: {}", self.message))
    }
}

/// Parse-time checks that jq's actions make with `block_is_const` and friends, which
/// need constant folding (compile.c, the value layer). The parser calls these at the
/// exact point jq's action runs, so the errors interleave with syntax errors in jq's
/// order (e.g. `[{(0):1} 2]` reports the key error first, then the syntax error).
///
/// Nodes passed here may contain error-recovery values ([`NodeKind::Error`] is
/// `gen_noop()`, never constant).
pub trait ParseHooks {
    /// `check_object_key` for `{(Query): ...}` (rule 165) and `{(Query): Pattern}`
    /// (rule 133). Return `Some("Cannot use number (0) as object key")` etc. when
    /// the key folds to a non-string constant; it's reported at the key's location.
    fn check_object_key(&mut self, key: &Node) -> Option<String> {
        let _ = key;
        None
    }

    /// Module and import metadata (rules 5 and 40). Return
    /// `Some("Module metadata must be constant")` or
    /// `Some("Module metadata must be an object")`, or `None` for a constant object.
    /// On error jq drops the directive, and so does the parser.
    fn check_metadata(&mut self, meta: &Node) -> Option<String> {
        let _ = meta;
        None
    }
}

/// Hooks that accept everything (no constant folding available).
pub struct NoHooks;

impl ParseHooks for NoHooks {}

/// Parse a jq program or module (port of `jq_parse`).
///
/// Returns the AST, or every error jq's parse would report, in order. jq prints each
/// with [`ParseError::render`] and then `jq: N compile error(s)`
/// ([`super::locfile::compile_errors_summary`]).
///
/// The input is raw bytes, like jq's (invalid UTF-8 is an `INVALID_CHARACTER`
/// outside strings and is replaced inside them). jq's CLI passes the program as a C
/// string, so callers should cut the text at the first NUL byte to match.
pub fn parse(src: &[u8], hooks: &mut dyn ParseHooks) -> Result<Program, Vec<ParseError>> {
    let mut p = Parser {
        lexer: Lexer::new(src),
        hooks,
        errors: Vec::new(),
        ss: Vec::with_capacity(YYINITDEPTH),
        vs: Vec::with_capacity(YYINITDEPTH),
        ls: Vec::with_capacity(YYINITDEPTH),
        answer: None,
    };
    let accepted = p.run();
    match (accepted, p.answer) {
        (true, Some(program)) if p.errors.is_empty() => Ok(program),
        _ => Err(p.errors),
    }
}

/// [`parse`] without semantic hooks.
pub fn parse_program(src: impl AsRef<[u8]>) -> Result<Program, Vec<ParseError>> {
    parse(src.as_ref(), &mut NoHooks)
}

/// Port of `jq_parse_library`, used for builtin.jq and imported modules: a library
/// may only contain definitions (plus `module`/`import` directives).
///
/// The main-expression error has no location, and jq formats it with a doubled
/// prefix: `jq: error: jq: error: library should only have function definitions, not
/// a main expression` (which is what [`ParseError::render`] produces).
pub fn parse_library(src: &[u8], hooks: &mut dyn ParseHooks) -> Result<Program, Vec<ParseError>> {
    let program = parse(src, hooks)?;
    if let ProgramBody::Main(_) = program.body {
        return Err(vec![ParseError {
            message: "library should only have function definitions, not a main expression".into(),
            loc: Loc::UNKNOWN,
        }]);
    }
    Ok(program)
}

/// `YYINITDEPTH`
const YYINITDEPTH: usize = 200;
/// `YYMAXDEPTH`: pushing the 10000th state fails with "memory exhausted".
const YYMAXDEPTH: usize = 10000;
/// `YYSYMBOL_YYerror`
const YYERROR_SYM: i32 = 1;

/// Semantic values on bison's value stack (`YYSTYPE`).
#[derive(Default)]
enum Sem {
    #[default]
    None,
    /// Token values; `Keyword`.
    Text(String),
    /// `Query`, `Expr`, `Term`, `Arg`, `DictExpr`.
    Node(Node),
    /// `ElseBody`.
    OptNode(Option<Node>),
    Module(Option<Module>),
    /// `Imports`, in reverse source order.
    Imports(Vec<Import>),
    /// `Import` (`None` when rule 40's metadata check failed).
    Import(Option<Import>),
    /// `ImportWhat`, `ImportFrom`-completed import without metadata.
    ImportWhat(Import),
    /// `ImportFrom`.
    ImportFrom(String),
    /// `FuncDefs`, in reverse source order.
    FuncDefs(Vec<FuncDef>),
    FuncDef(FuncDef),
    Params(Vec<Param>),
    Param(Param),
    StringStart(Option<String>),
    Str(StringLit),
    QQString(Vec<StrPart>),
    Args(Vec<Node>),
    /// `RepPatterns`, `Patterns`, `ArrayPats`.
    Patterns(Vec<Pattern>),
    Pattern(Pattern),
    ObjPats(Vec<ObjPat>),
    ObjPat(ObjPat),
    /// `DictPairs`, in reverse source order.
    DictPairs(Vec<DictPair>),
    DictPair(DictPair),
}

macro_rules! sem_into {
    ($name:ident, $variant:ident, $ty:ty) => {
        fn $name(self) -> $ty {
            match self {
                Sem::$variant(v) => v,
                _ => unreachable!(concat!(
                    "parser value stack: expected ",
                    stringify!($variant)
                )),
            }
        }
    };
}

impl Sem {
    sem_into!(text, Text, String);
    sem_into!(node, Node, Node);
    sem_into!(opt_node, OptNode, Option<Node>);
    sem_into!(module, Module, Option<Module>);
    sem_into!(imports, Imports, Vec<Import>);
    sem_into!(import, Import, Option<Import>);
    sem_into!(import_what, ImportWhat, Import);
    sem_into!(import_from, ImportFrom, String);
    sem_into!(func_defs, FuncDefs, Vec<FuncDef>);
    sem_into!(func_def, FuncDef, FuncDef);
    sem_into!(params, Params, Vec<Param>);
    sem_into!(param, Param, Param);
    sem_into!(string_start, StringStart, Option<String>);
    sem_into!(string, Str, StringLit);
    sem_into!(qqstring, QQString, Vec<StrPart>);
    sem_into!(args, Args, Vec<Node>);
    sem_into!(patterns, Patterns, Vec<Pattern>);
    sem_into!(pattern, Pattern, Pattern);
    sem_into!(obj_pats, ObjPats, Vec<ObjPat>);
    sem_into!(obj_pat, ObjPat, ObjPat);
    sem_into!(dict_pairs, DictPairs, Vec<DictPair>);
    sem_into!(dict_pair, DictPair, DictPair);
}

struct Parser<'a, 'h> {
    lexer: Lexer<'a>,
    hooks: &'h mut dyn ParseHooks,
    errors: Vec<ParseError>,
    /// State, value and location stacks (`yyss`, `yyvs`, `yyls`).
    ss: Vec<i32>,
    vs: Vec<Sem>,
    ls: Vec<Loc>,
    answer: Option<Program>,
}

/// Where control goes next in the skeleton (its labels).
enum Step {
    NewState,
    Default,
    Reduce(usize),
    ErrLab,
    ErrLab1,
}

#[inline]
fn b(n: Node) -> Box<Node> {
    Box::new(n)
}

fn binop_for_rule(rule: usize) -> BinOp {
    match rule {
        16 => BinOp::Alt,
        17 => BinOp::Assign,
        18 => BinOp::Or,
        19 => BinOp::And,
        20 => BinOp::AltAssign,
        21 => BinOp::Update,
        22 => BinOp::Add,
        23 => BinOp::AddAssign,
        24 => BinOp::Sub,
        25 => BinOp::SubAssign,
        26 => BinOp::Mul,
        27 => BinOp::MulAssign,
        28 => BinOp::Div,
        29 => BinOp::Mod,
        30 => BinOp::DivAssign,
        31 => BinOp::ModAssign,
        32 => BinOp::Eq,
        33 => BinOp::Ne,
        34 => BinOp::Lt,
        35 => BinOp::Gt,
        36 => BinOp::Le,
        37 => BinOp::Ge,
        _ => unreachable!(),
    }
}

/// `yysyntax_error` with `yy_syntax_error_arguments` and
/// `yypcontext_expected_tokens`: "syntax error, unexpected X[, expecting A or B...]",
/// listing at most four expected tokens (none if there are more).
fn syntax_error_message(state: i32, token: Option<u8>) -> String {
    let mut args: Vec<u8> = Vec::with_capacity(5);
    if let Some(tok) = token {
        args.push(tok);
        let yyn = YYPACT[state as usize] as i32;
        let mut expected: Vec<u8> = Vec::with_capacity(4);
        let mut too_many = false;
        if yyn != YYPACT_NINF as i32 {
            let xbegin = if yyn < 0 { -yyn } else { 0 };
            let checklim = YYLAST - yyn + 1;
            let xend = checklim.min(YYNTOKENS);
            for x in xbegin..xend {
                let i = (x + yyn) as usize;
                if YYCHECK[i] as i32 == x && x != YYERROR_SYM && YYTABLE[i] != YYTABLE_NINF {
                    if expected.len() == 4 {
                        too_many = true;
                        break;
                    }
                    expected.push(x as u8);
                }
            }
        }
        if !too_many {
            args.extend(expected);
        }
    }
    let mut msg = String::from("syntax error");
    for (i, &a) in args.iter().enumerate() {
        msg.push_str(match i {
            0 => ", unexpected ",
            1 => ", expecting ",
            _ => " or ",
        });
        msg.push_str(YYTNAME[a as usize]);
    }
    msg
}

impl Parser<'_, '_> {
    /// `FAIL(loc, msg)` / `yyerror`.
    fn fail(&mut self, loc: Loc, msg: impl Into<String>) {
        self.errors.push(ParseError {
            message: msg.into(),
            loc,
        });
    }

    /// Push a state and check the stack limit (`yynewstate` + `yysetstate`).
    /// Returns false on "memory exhausted".
    #[inline]
    fn push_state(&mut self, state: i32) -> bool {
        self.ss.push(state);
        self.ss.len() < YYMAXDEPTH
    }

    /// `yyparse`. Returns true when the input was accepted (possibly after errors
    /// were reported and recovered from).
    fn run(&mut self) -> bool {
        // Lookahead symbol kind; None is YYEMPTY.
        let mut yychar: Option<u8> = None;
        let mut yylval: Option<Token> = None;
        // The lookahead location. jq's YYLTYPE isn't "trivial", so the initial value is
        // the zero-initialized static `yyloc_default`.
        let mut yylloc = Loc::new(0, 0);
        let mut yyerrstatus = 0;
        let mut yyerror_range1 = Loc::default();
        let mut yystate: i32 = 0;

        self.ss.push(0);
        self.vs.push(Sem::None);
        self.ls.push(yylloc);
        let mut step = Step::NewState;
        loop {
            step = match step {
                // yysetstate (the state was pushed by `push_state`)
                Step::NewState => {
                    if yystate == YYFINAL {
                        return true;
                    }
                    // yybackup
                    let mut yyn = YYPACT[yystate as usize] as i32;
                    if yyn == YYPACT_NINF as i32 {
                        Step::Default
                    } else {
                        if yychar.is_none() {
                            let tok = self.lexer.next_token(&mut yylloc);
                            if let Some(msg) = &tok.error {
                                // yylex's wrapper: FAIL(*yylloc, msg) for bad literals
                                let msg = msg.clone();
                                self.fail(yylloc, msg);
                            }
                            yychar = Some(tok.sym);
                            yylval = Some(tok);
                        }
                        let yytoken = yychar.unwrap() as i32;
                        yyn += yytoken;
                        if !(0..=YYLAST).contains(&yyn) || YYCHECK[yyn as usize] as i32 != yytoken {
                            Step::Default
                        } else {
                            let action = YYTABLE[yyn as usize] as i32;
                            if action <= 0 {
                                if action == YYTABLE_NINF as i32 {
                                    Step::ErrLab
                                } else {
                                    Step::Reduce((-action) as usize)
                                }
                            } else {
                                // Shift the lookahead token.
                                if yyerrstatus > 0 {
                                    yyerrstatus -= 1;
                                }
                                yystate = action;
                                let tok = yylval.take().unwrap();
                                self.vs.push(match tok.text {
                                    Some(t) => Sem::Text(t),
                                    None => Sem::None,
                                });
                                self.ls.push(yylloc);
                                yychar = None;
                                if !self.push_state(yystate) {
                                    self.fail(yylloc, "memory exhausted");
                                    return false;
                                }
                                Step::NewState
                            }
                        }
                    }
                }
                Step::Default => {
                    let rule = YYDEFACT[yystate as usize] as usize;
                    if rule == 0 {
                        Step::ErrLab
                    } else {
                        Step::Reduce(rule)
                    }
                }
                Step::Reduce(rule) => {
                    let len = YYR2[rule] as usize;
                    let base = self.ss.len() - len;
                    // YYLLOC_DEFAULT
                    let loc = if len > 0 {
                        Loc::new(self.ls[base].start, self.ls[base + len - 1].end)
                    } else {
                        let prev = self.ls[base - 1];
                        Loc::new(prev.end, prev.end)
                    };
                    let value = self.action(rule, loc, base);
                    self.ss.truncate(base);
                    self.vs.truncate(base);
                    self.ls.truncate(base);
                    self.vs.push(value);
                    self.ls.push(loc);
                    let lhs = YYR1[rule] as i32 - YYNTOKENS;
                    let top = *self.ss.last().unwrap();
                    let i = YYPGOTO[lhs as usize] as i32 + top;
                    yystate = if (0..=YYLAST).contains(&i) && YYCHECK[i as usize] as i32 == top {
                        YYTABLE[i as usize] as i32
                    } else {
                        YYDEFGOTO[lhs as usize] as i32
                    };
                    if !self.push_state(yystate) {
                        self.fail(yylloc, "memory exhausted");
                        return false;
                    }
                    Step::NewState
                }
                Step::ErrLab => {
                    // If not already recovering from an error, report this error.
                    if yyerrstatus == 0 {
                        let msg = syntax_error_message(yystate, yychar);
                        self.fail(yylloc, msg);
                    }
                    yyerror_range1 = yylloc;
                    if yyerrstatus == 3 {
                        // If just tried and failed to reuse lookahead token after an
                        // error, discard it.
                        match yychar {
                            Some(0) => return false, // at end of input: YYABORT
                            None => {}
                            Some(_) => {
                                yychar = None;
                                yylval = None;
                            }
                        }
                    }
                    Step::ErrLab1
                }
                Step::ErrLab1 => {
                    yyerrstatus = 3; // Each real token shifted decrements this.
                    // Pop the stack until a state that shifts the error token.
                    let target = loop {
                        let mut yyn = YYPACT[yystate as usize] as i32;
                        if yyn != YYPACT_NINF as i32 {
                            yyn += YYERROR_SYM;
                            if (0..=YYLAST).contains(&yyn)
                                && YYCHECK[yyn as usize] as i32 == YYERROR_SYM
                            {
                                let t = YYTABLE[yyn as usize] as i32;
                                if 0 < t {
                                    break t;
                                }
                            }
                        }
                        if self.ss.len() == 1 {
                            return false; // YYABORT
                        }
                        yyerror_range1 = *self.ls.last().unwrap();
                        self.ss.pop();
                        self.vs.pop();
                        self.ls.pop();
                        yystate = *self.ss.last().unwrap();
                    };
                    self.vs.push(Sem::None);
                    // YYLLOC_DEFAULT(*yylsp, yyerror_range, 2)
                    self.ls.push(Loc::new(yyerror_range1.start, yylloc.end));
                    yystate = target;
                    if !self.push_state(yystate) {
                        self.fail(yylloc, "memory exhausted");
                        return false;
                    }
                    Step::NewState
                }
            };
        }
    }

    /// `$k` of the rule being reduced (moved out of the value stack).
    #[inline]
    fn take(&mut self, base: usize, k: usize) -> Sem {
        std::mem::take(&mut self.vs[base + k - 1])
    }

    /// `@k` of the rule being reduced.
    #[inline]
    fn at(&self, base: usize, k: usize) -> Loc {
        self.ls[base + k - 1]
    }

    /// The semantic actions of parser.y, rule by rule.
    fn action(&mut self, rule: usize, loc: Loc, base: usize) -> Sem {
        macro_rules! v {
            ($k:expr) => {
                self.take(base, $k)
            };
        }
        macro_rules! node {
            ($kind:expr) => {
                Sem::Node(Node::new($kind, loc))
            };
        }
        match rule {
            // TopLevel: Module Imports Query
            2 | 3 => {
                let module = v!(1).module();
                let mut imports = v!(2).imports();
                imports.reverse();
                let body = if rule == 2 {
                    ProgramBody::Main(v!(3).node())
                } else {
                    let mut defs = v!(3).func_defs();
                    defs.reverse();
                    ProgramBody::Library(defs)
                };
                self.answer = Some(Program {
                    module,
                    imports,
                    body,
                });
                Sem::None
            }
            // Module: %empty
            4 => Sem::Module(None),
            // Module: "module" Query ';'
            5 => {
                let meta = v!(2).node();
                let meta_loc = self.at(base, 2);
                match self.hooks.check_metadata(&meta) {
                    Some(msg) => {
                        self.fail(meta_loc, msg);
                        Sem::Module(None)
                    }
                    None => Sem::Module(Some(Module {
                        meta,
                        meta_loc,
                        loc,
                    })),
                }
            }
            // Imports: %empty
            6 => Sem::Imports(Vec::new()),
            // Imports: Import Imports
            7 => {
                let import = v!(1).import();
                let mut rest = v!(2).imports();
                rest.extend(import);
                Sem::Imports(rest)
            }
            // FuncDefs: %empty
            8 => Sem::FuncDefs(Vec::new()),
            // FuncDefs: FuncDef FuncDefs
            9 => {
                let def = v!(1).func_def();
                let mut rest = v!(2).func_defs();
                rest.push(def);
                Sem::FuncDefs(rest)
            }
            // Query: FuncDef Query %prec FUNCDEF
            10 => {
                let def = v!(1).func_def();
                let rest = v!(2).node();
                node!(NodeKind::FuncDef {
                    def: Box::new(def),
                    rest: b(rest),
                })
            }
            // Query: Expr "as" Patterns '|' Query
            11 => {
                let source = v!(1).node();
                let patterns = v!(3).patterns();
                let body = v!(5).node();
                node!(NodeKind::As {
                    source: b(source),
                    patterns,
                    body: b(body),
                })
            }
            // Query: "label" BINDING '|' Query
            12 => {
                let name = v!(2).text();
                let body = v!(4).node();
                node!(NodeKind::Label {
                    name,
                    body: b(body)
                })
            }
            // Query: Query '|' Query
            13 | 167 => {
                let a = v!(1).node();
                let c = v!(3).node();
                node!(NodeKind::Pipe(b(a), b(c)))
            }
            // Query: Query ',' Query
            14 => {
                let a = v!(1).node();
                let c = v!(3).node();
                node!(NodeKind::Comma(b(a), b(c)))
            }
            // Query: Expr; Expr: Term; Arg: Query; DictExpr: Expr
            15 | 38 | 116 | 168 => v!(1),
            // Expr: Expr <op> Expr
            16..=37 => {
                let lhs = v!(1).node();
                let rhs = v!(3).node();
                node!(NodeKind::Binary {
                    op: binop_for_rule(rule),
                    lhs: b(lhs),
                    rhs: b(rhs),
                })
            }
            // Import: ImportWhat ';'
            39 => {
                let mut import = v!(1).import_what();
                import.loc = loc;
                Sem::Import(Some(import))
            }
            // Import: ImportWhat Query ';'
            40 => {
                let mut import = v!(1).import_what();
                let meta = v!(2).node();
                let meta_loc = self.at(base, 2);
                match self.hooks.check_metadata(&meta) {
                    Some(msg) => {
                        self.fail(meta_loc, msg);
                        Sem::Import(None)
                    }
                    None => {
                        import.meta = Some(meta);
                        import.meta_loc = Some(meta_loc);
                        import.loc = loc;
                        Sem::Import(Some(import))
                    }
                }
            }
            // ImportWhat: "import" ImportFrom "as" BINDING | "import" ImportFrom "as" IDENT
            41 | 42 => {
                let path = v!(2).import_from();
                let name = v!(4).text();
                Sem::ImportWhat(Import {
                    path,
                    path_loc: self.at(base, 2),
                    kind: if rule == 41 {
                        ImportKind::Data(name)
                    } else {
                        ImportKind::Code(name)
                    },
                    meta: None,
                    meta_loc: None,
                    loc,
                })
            }
            // ImportWhat: "include" ImportFrom
            43 => {
                let path = v!(2).import_from();
                Sem::ImportWhat(Import {
                    path,
                    path_loc: self.at(base, 2),
                    kind: ImportKind::Include,
                    meta: None,
                    meta_loc: None,
                    loc,
                })
            }
            // ImportFrom: String
            44 => {
                let s = v!(1).string();
                match s.constant_value() {
                    Some(path) => Sem::ImportFrom(path),
                    None => {
                        self.fail(self.at(base, 1), "Import path must be constant");
                        Sem::ImportFrom(String::new())
                    }
                }
            }
            // FuncDef: "def" IDENT ':' Query ';'
            45 => {
                let name = v!(2).text();
                let body = v!(4).node();
                Sem::FuncDef(FuncDef {
                    name,
                    params: Vec::new(),
                    body,
                    loc,
                })
            }
            // FuncDef: "def" IDENT '(' Params ')' ':' Query ';'
            46 => {
                let name = v!(2).text();
                let params = v!(4).params();
                let body = v!(7).node();
                Sem::FuncDef(FuncDef {
                    name,
                    params,
                    body,
                    loc,
                })
            }
            // Params: Param
            47 => Sem::Params(vec![v!(1).param()]),
            // Params: Params ';' Param
            48 => {
                let mut params = v!(1).params();
                params.push(v!(3).param());
                Sem::Params(params)
            }
            // Param: BINDING | IDENT
            49 | 50 => Sem::Param(Param {
                name: v!(1).text(),
                kind: if rule == 49 {
                    ParamKind::Value
                } else {
                    ParamKind::Filter
                },
                loc,
            }),
            // StringStart: FORMAT QQSTRING_START
            51 => Sem::StringStart(Some(v!(1).text())),
            // StringStart: QQSTRING_START
            52 => Sem::StringStart(None),
            // String: StringStart QQString QQSTRING_END
            53 => {
                let format = v!(1).string_start();
                let parts = v!(2).qqstring();
                Sem::Str(StringLit { format, parts, loc })
            }
            // QQString: %empty
            54 => Sem::QQString(Vec::new()),
            // QQString: QQString QQSTRING_TEXT
            55 => {
                let mut parts = v!(1).qqstring();
                parts.push(StrPart::Text(v!(2).text()));
                Sem::QQString(parts)
            }
            // QQString: QQString QQSTRING_INTERP_START Query QQSTRING_INTERP_END
            56 => {
                let mut parts = v!(1).qqstring();
                parts.push(StrPart::Interp(v!(3).node()));
                Sem::QQString(parts)
            }
            // ElseBody: "elif" Query "then" Query ElseBody
            57 => {
                let cond = v!(2).node();
                let then_ = v!(4).node();
                let else_ = v!(5).opt_node();
                Sem::OptNode(Some(Node::new(
                    NodeKind::If {
                        cond: b(cond),
                        then_: b(then_),
                        else_: else_.map(b),
                    },
                    loc,
                )))
            }
            // ElseBody: "else" Query "end"
            58 => Sem::OptNode(Some(v!(2).node())),
            // ElseBody: "end"
            59 => Sem::OptNode(None),
            // Term: '.'
            60 => node!(NodeKind::Identity),
            // Term: ".."
            61 => node!(NodeKind::Recurse),
            // Term: "break" BINDING
            62 => node!(NodeKind::Break(v!(2).text())),
            // Term: "break" error
            63 => {
                self.fail(loc, "break requires a label to break to");
                node!(NodeKind::Error)
            }
            // Term: Term FIELD '?' | Term FIELD
            64 | 68 => {
                let target = v!(1).node();
                let key = Node::new(
                    NodeKind::Literal(Literal::String(v!(2).text())),
                    self.at(base, 2),
                );
                node!(NodeKind::Index {
                    target: Some(b(target)),
                    key: b(key),
                    optional: rule == 64,
                })
            }
            // Term: FIELD '?' | FIELD
            65 | 69 => {
                let key = Node::new(
                    NodeKind::Literal(Literal::String(v!(1).text())),
                    self.at(base, 1),
                );
                node!(NodeKind::Index {
                    target: None,
                    key: b(key),
                    optional: rule == 65,
                })
            }
            // Term: Term '.' String '?' | Term '.' String
            66 | 70 => {
                let target = v!(1).node();
                let s = v!(3).string();
                let key = Node::new(NodeKind::Str(Box::new(s)), self.at(base, 3));
                node!(NodeKind::Index {
                    target: Some(b(target)),
                    key: b(key),
                    optional: rule == 66,
                })
            }
            // Term: '.' String '?' | '.' String
            67 | 71 => {
                let s = v!(2).string();
                let key = Node::new(NodeKind::Str(Box::new(s)), self.at(base, 2));
                node!(NodeKind::Index {
                    target: None,
                    key: b(key),
                    optional: rule == 67,
                })
            }
            // Term: '.' error | '.' IDENT error
            72 | 73 => {
                self.fail(
                    loc,
                    "try .[\"field\"] instead of .field for unusually named fields",
                );
                node!(NodeKind::Error)
            }
            // Term: Term '[' Query ']' ['?']
            74 | 75 => {
                let target = v!(1).node();
                let key = v!(3).node();
                node!(NodeKind::Index {
                    target: Some(b(target)),
                    key: b(key),
                    optional: rule == 74,
                })
            }
            // Term: Term '.' '[' Query ']' ['?']
            76 | 77 => {
                let target = v!(1).node();
                let key = v!(4).node();
                node!(NodeKind::Index {
                    target: Some(b(target)),
                    key: b(key),
                    optional: rule == 76,
                })
            }
            // Term: Term '[' ']' ['?'] | Term '.' '[' ']' ['?']
            78..=81 => {
                let target = v!(1).node();
                node!(NodeKind::Each {
                    target: b(target),
                    optional: rule == 78 || rule == 80,
                })
            }
            // Term: Term '[' Query ':' Query ']' ['?']
            82 | 85 => {
                let target = v!(1).node();
                let from = v!(3).node();
                let to = v!(5).node();
                node!(NodeKind::Slice {
                    target: b(target),
                    from: Some(b(from)),
                    to: Some(b(to)),
                    optional: rule == 82,
                })
            }
            // Term: Term '[' Query ':' ']' ['?']
            83 | 86 => {
                let target = v!(1).node();
                let from = v!(3).node();
                node!(NodeKind::Slice {
                    target: b(target),
                    from: Some(b(from)),
                    to: None,
                    optional: rule == 83,
                })
            }
            // Term: Term '[' ':' Query ']' ['?']
            84 | 87 => {
                let target = v!(1).node();
                let to = v!(4).node();
                node!(NodeKind::Slice {
                    target: b(target),
                    from: None,
                    to: Some(b(to)),
                    optional: rule == 84,
                })
            }
            // Term: Term '?'
            88 => node!(NodeKind::Optional(b(v!(1).node()))),
            // Term: LITERAL
            89 => node!(NodeKind::Literal(Literal::Number(v!(1).text()))),
            // Term: String
            90 => node!(NodeKind::Str(Box::new(v!(1).string()))),
            // Term: FORMAT
            91 => node!(NodeKind::Format(v!(1).text())),
            // Term: '-' Term
            92 => node!(NodeKind::Neg(b(v!(2).node()))),
            // Term: '(' Query ')'
            93 => v!(2),
            // Term: '[' Query ']'
            94 => node!(NodeKind::Array(Some(b(v!(2).node())))),
            // Term: '[' ']'
            95 => node!(NodeKind::Array(None)),
            // Term: '{' DictPairs '}'
            96 => {
                let mut pairs = v!(2).dict_pairs();
                pairs.reverse();
                node!(NodeKind::Object(pairs))
            }
            // Term: "reduce" Expr "as" Patterns '(' Query ';' Query ')'
            97 => {
                let source = v!(2).node();
                let patterns = v!(4).patterns();
                let init = v!(6).node();
                let update = v!(8).node();
                node!(NodeKind::Reduce {
                    source: b(source),
                    patterns,
                    init: b(init),
                    update: b(update),
                })
            }
            // Term: "foreach" Expr "as" Patterns '(' Query ';' Query [';' Query] ')'
            98 | 99 => {
                let source = v!(2).node();
                let patterns = v!(4).patterns();
                let init = v!(6).node();
                let update = v!(8).node();
                let extract = if rule == 98 {
                    Some(b(v!(10).node()))
                } else {
                    None
                };
                node!(NodeKind::Foreach {
                    source: b(source),
                    patterns,
                    init: b(init),
                    update: b(update),
                    extract,
                })
            }
            // Term: "if" Query "then" Query ElseBody
            100 => {
                let cond = v!(2).node();
                let then_ = v!(4).node();
                let else_ = v!(5).opt_node();
                node!(NodeKind::If {
                    cond: b(cond),
                    then_: b(then_),
                    else_: else_.map(b),
                })
            }
            // Term: "if" Query "then" error  ($$ = $2)
            101 => {
                self.fail(loc, "Possibly unterminated 'if' statement");
                v!(2)
            }
            // Term: "try" Expr "catch" Expr
            102 => {
                let body = v!(2).node();
                let handler = v!(4).node();
                node!(NodeKind::Try {
                    body: b(body),
                    handler: Some(b(handler)),
                })
            }
            // Term: "try" Expr "catch" error  ($$ = $2)
            103 => {
                self.fail(loc, "Possibly unterminated 'try' statement");
                v!(2)
            }
            // Term: "try" Expr
            104 => node!(NodeKind::Try {
                body: b(v!(2).node()),
                handler: None,
            }),
            // Term: '$' '$' '$' BINDING
            105 => node!(NodeKind::VarTake(v!(4).text())),
            // Term: BINDING
            106 => node!(NodeKind::Var(v!(1).text())),
            // Term: "$__loc__"
            107 => node!(NodeKind::LocObject),
            // Term: IDENT
            108 => {
                let name = v!(1).text();
                node!(match name.as_str() {
                    "false" => NodeKind::Literal(Literal::False),
                    "true" => NodeKind::Literal(Literal::True),
                    "null" => NodeKind::Literal(Literal::Null),
                    _ => NodeKind::Call {
                        name,
                        args: Vec::new(),
                        name_loc: loc,
                    },
                })
            }
            // Term: IDENT '(' Args ')'
            109 => {
                let name = v!(1).text();
                let args = v!(3).args();
                node!(NodeKind::Call {
                    name,
                    args,
                    name_loc: self.at(base, 1),
                })
            }
            // Term: '(' error ')' | '[' error ']' | '{' error '}'
            110 | 111 | 113 => node!(NodeKind::Error),
            // Term: Term '[' error ']'  ($$ = $1)
            112 => v!(1),
            // Args: Arg
            114 => Sem::Args(vec![v!(1).node()]),
            // Args: Args ';' Arg
            115 => {
                let mut args = v!(1).args();
                args.push(v!(3).node());
                Sem::Args(args)
            }
            // RepPatterns: RepPatterns "?//" Pattern; Patterns: RepPatterns "?//" Pattern;
            // ArrayPats: ArrayPats ',' Pattern
            117 | 119 | 125 => {
                let mut pats = v!(1).patterns();
                pats.push(v!(3).pattern());
                Sem::Patterns(pats)
            }
            // RepPatterns: Pattern; Patterns: Pattern; ArrayPats: Pattern
            118 | 120 | 124 => Sem::Patterns(vec![v!(1).pattern()]),
            // Pattern: BINDING
            121 => Sem::Pattern(Pattern {
                kind: PatternKind::Var(v!(1).text()),
                loc,
            }),
            // Pattern: '[' ArrayPats ']'
            122 => Sem::Pattern(Pattern {
                kind: PatternKind::Array(v!(2).patterns()),
                loc,
            }),
            // Pattern: '{' ObjPats '}'
            123 => Sem::Pattern(Pattern {
                kind: PatternKind::Object(v!(2).obj_pats()),
                loc,
            }),
            // ObjPats: ObjPat
            126 => Sem::ObjPats(vec![v!(1).obj_pat()]),
            // ObjPats: ObjPats ',' ObjPat
            127 => {
                let mut pats = v!(1).obj_pats();
                pats.push(v!(3).obj_pat());
                Sem::ObjPats(pats)
            }
            // ObjPat: BINDING
            128 => Sem::ObjPat(ObjPat {
                kind: ObjPatKind::Var(v!(1).text()),
                loc,
            }),
            // ObjPat: BINDING ':' Pattern
            129 => {
                let name = v!(1).text();
                let pat = v!(3).pattern();
                Sem::ObjPat(ObjPat {
                    kind: ObjPatKind::VarPattern(name, pat),
                    loc,
                })
            }
            // ObjPat: IDENT ':' Pattern | Keyword ':' Pattern
            130 | 131 => {
                let name = v!(1).text();
                let pat = v!(3).pattern();
                Sem::ObjPat(ObjPat {
                    kind: ObjPatKind::Named(name, pat),
                    loc,
                })
            }
            // ObjPat: String ':' Pattern
            132 => {
                let key = v!(1).string();
                let pat = v!(3).pattern();
                Sem::ObjPat(ObjPat {
                    kind: ObjPatKind::Str(key, pat),
                    loc,
                })
            }
            // ObjPat: '(' Query ')' ':' Pattern
            133 => {
                let key = v!(2).node();
                let key_loc = self.at(base, 2);
                if let Some(msg) = self.hooks.check_object_key(&key) {
                    self.fail(key_loc, msg);
                }
                let pattern = v!(5).pattern();
                Sem::ObjPat(ObjPat {
                    kind: ObjPatKind::Computed {
                        key,
                        key_loc,
                        pattern,
                    },
                    loc,
                })
            }
            // ObjPat: error ':' Pattern
            134 => {
                self.fail(loc, "May need parentheses around object key expression");
                let pat = v!(3).pattern();
                Sem::ObjPat(ObjPat {
                    kind: ObjPatKind::Error(pat),
                    loc,
                })
            }
            // Keyword: "as" | "def" | ... | "break"
            135..=152 => Sem::Text(
                match rule {
                    135 => "as",
                    136 => "def",
                    137 => "module",
                    138 => "import",
                    139 => "include",
                    140 => "if",
                    141 => "then",
                    142 => "else",
                    143 => "elif",
                    144 => "reduce",
                    145 => "foreach",
                    146 => "end",
                    147 => "and",
                    148 => "or",
                    149 => "try",
                    150 => "catch",
                    151 => "label",
                    _ => "break",
                }
                .to_string(),
            ),
            // DictPairs: %empty
            153 => Sem::DictPairs(Vec::new()),
            // DictPairs: DictPair
            154 => Sem::DictPairs(vec![v!(1).dict_pair()]),
            // DictPairs: DictPair ',' DictPairs
            155 => {
                let pair = v!(1).dict_pair();
                let mut rest = v!(3).dict_pairs();
                rest.push(pair);
                Sem::DictPairs(rest)
            }
            // DictPair: IDENT ':' DictExpr | Keyword ':' DictExpr
            156 | 157 => {
                let key = v!(1).text();
                let value = v!(3).node();
                Sem::DictPair(DictPair {
                    kind: DictPairKind::Named { key, value },
                    loc,
                })
            }
            // DictPair: String ':' DictExpr
            158 => {
                let key = v!(1).string();
                let value = v!(3).node();
                Sem::DictPair(DictPair {
                    kind: DictPairKind::Str { key, value },
                    loc,
                })
            }
            // DictPair: String
            159 => Sem::DictPair(DictPair {
                kind: DictPairKind::StrShorthand(v!(1).string()),
                loc,
            }),
            // DictPair: BINDING ':' DictExpr
            160 => {
                let name = v!(1).text();
                let value = v!(3).node();
                Sem::DictPair(DictPair {
                    kind: DictPairKind::VarKey { name, value },
                    loc,
                })
            }
            // DictPair: BINDING
            161 => Sem::DictPair(DictPair {
                kind: DictPairKind::Var(v!(1).text()),
                loc,
            }),
            // DictPair: IDENT | Keyword
            162 | 164 => Sem::DictPair(DictPair {
                kind: DictPairKind::NameShorthand(v!(1).text()),
                loc,
            }),
            // DictPair: "$__loc__"
            163 => Sem::DictPair(DictPair {
                kind: DictPairKind::LocObject,
                loc,
            }),
            // DictPair: '(' Query ')' ':' DictExpr
            165 => {
                let key = v!(2).node();
                let key_loc = self.at(base, 2);
                if let Some(msg) = self.hooks.check_object_key(&key) {
                    self.fail(key_loc, msg);
                }
                let value = v!(5).node();
                Sem::DictPair(DictPair {
                    kind: DictPairKind::Computed {
                        key,
                        key_loc,
                        value,
                    },
                    loc,
                })
            }
            // DictPair: error ':' DictExpr
            166 => {
                self.fail(
                    self.at(base, 1),
                    "May need parentheses around object key expression",
                );
                let value = v!(3).node();
                Sem::DictPair(DictPair {
                    kind: DictPairKind::Error(value),
                    loc,
                })
            }
            _ => unreachable!("no action for rule {rule}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::jq::lang::locfile::LocFile;

    fn sexpr(src: &str) -> String {
        match parse_program(src) {
            Ok(p) => p.to_sexpr(),
            Err(errors) => panic!("{src:?} failed to parse: {errors:?}"),
        }
    }

    fn first_error(src: &str) -> String {
        match parse_program(src) {
            Ok(p) => panic!("{src:?} parsed: {}", p.to_sexpr()),
            Err(errors) => errors[0].message.clone(),
        }
    }

    fn check(cases: &[(&str, &str)]) {
        for (src, want) in cases {
            assert_eq!(sexpr(src), *want, "{src}");
        }
    }

    #[test]
    fn precedence_and_associativity() {
        check(&[
            ("1 + 2 * 3", "(+ 1 (* 2 3))"),
            ("1 - 2 - 3", "(- (- 1 2) 3)"),
            ("1 * 2 / 3 % 4", "(% (/ (* 1 2) 3) 4)"),
            ("1, 2 | 3, 4", "(| (, 1 2) (, 3 4))"),
            ("1 | 2 | 3", "(| 1 (| 2 3))"),
            ("1, 2, 3", "(, (, 1 2) 3)"),
            (
                ".a // .b // .c",
                "(// (index . \"a\") (// (index . \"b\") (index . \"c\")))",
            ),
            (
                ".a // .b | .c",
                "(| (// (index . \"a\") (index . \"b\")) (index . \"c\"))",
            ),
            // assignment binds tighter than `//` (`.a = .b // 5` yields {"a":null})
            (".a = .b // 5", "(// (= (index . \"a\") (index . \"b\")) 5)"),
            (".a |= . + 1", "(|= (index . \"a\") (+ . 1))"),
            (".a += 1 | .b", "(| (+= (index . \"a\") 1) (index . \"b\"))"),
            (". //= 1", "(//= . 1)"),
            ("1 == 2 and 3", "(and (== 1 2) 3)"),
            ("1 or 2 and 3", "(or 1 (and 2 3))"),
            ("1 // 2 or 3", "(// 1 (or 2 3))"),
        ]);
        // comparison and assignment operators are %nonassoc
        assert_eq!(first_error("1 < 2 < 3"), "syntax error, unexpected '<'");
        assert_eq!(first_error("1 == 2 == 3"), "syntax error, unexpected ==");
        assert_eq!(first_error(".a = 1 = 2"), "syntax error, unexpected '='");
        assert_eq!(first_error("1 < 2 == true"), "syntax error, unexpected ==");
    }

    #[test]
    fn unary_minus_and_postfix() {
        check(&[
            ("-1", "(neg 1)"),
            ("--1", "(neg (neg 1))"),
            ("-1 + 2", "(+ (neg 1) 2)"),
            ("1 - -1", "(- 1 (neg 1))"),
            ("-.a.b", "(neg (index (index . \"a\") \"b\"))"),
            ("-1?", "(neg (? 1))"),
            (".a.b[0]", "(index (index (index . \"a\") \"b\") 0)"),
            (".a?", "(index? . \"a\")"),
            (".a??", "(? (index? . \"a\"))"),
            ("(.a)?", "(? (index . \"a\"))"),
            (".a?.b", "(index (index? . \"a\") \"b\")"),
            (".[]?", "(each? .)"),
            (".a[]", "(each (index . \"a\"))"),
            (".a.[]?", "(each? (index . \"a\"))"),
            ("..?", "(? ..)"),
            ("..[]", "(each ..)"),
            (".. .a", "(index .. \"a\")"),
            (".\"foo\"", "(index . \"foo\")"),
            (".\"foo\"?", "(index? . \"foo\")"),
            (
                ".a.\"b\\(1)\"",
                "(index (index . \"a\") (str \"b\" (interp 1)))",
            ),
            (".@base64 \"x\"", "(index . (str @base64 \"x\"))"),
            (".[1:2]", "(slice . 1 2)"),
            (".[:2]", "(slice . _ 2)"),
            (".[1:]?", "(slice? . 1 _)"),
            (".foo[1:2]", "(slice (index . \"foo\") 1 2)"),
            (".a.[1]", "(index (index . \"a\") 1)"),
            (". [0]", "(index . 0)"),
            ("1 .a", "(index 1 \"a\")"),
            (".e5", "(index . \"e5\")"),
            (".5", ".5"),
            ("1.e5", "1.e5"),
            ("$__loc__.file", "(index $__loc__ \"file\")"),
            ("{a: 1}.a", "(index (object (\"a\" 1)) \"a\")"),
        ]);
        assert_eq!(
            first_error(".a.[1:2]"),
            "syntax error, unexpected ':', expecting '|' or ',' or ']'"
        );
        assert_eq!(
            first_error("..a"),
            "syntax error, unexpected IDENT, expecting end of file"
        );
        assert_eq!(
            first_error("1.a"),
            "syntax error, unexpected IDENT, expecting end of file"
        );
        assert_eq!(first_error(".[:]"), "syntax error, unexpected ']'");
        // `?//` is one token, so `.a?//1` is not `.a? // 1`
        assert_eq!(
            first_error(".a?//1"),
            "syntax error, unexpected ?//, expecting end of file"
        );
        assert_eq!(sexpr(".a? // 1"), "(// (index? . \"a\") 1)");
    }

    #[test]
    fn keyword_forms() {
        check(&[
            ("try .a catch .b", "(try (index . \"a\") (index . \"b\"))"),
            // a try body or handler is a postfix term: operators end it
            ("try 1 + 1", "(+ (try 1) 1)"),
            ("try 1 catch 2 | 3", "(| (try 1 2) 3)"),
            ("try -1", "(try (neg 1))"),
            ("try try 1 catch 2 catch 3", "(try (try 1 2) 3)"),
            ("if . then 1 end", "(if . 1)"),
            (
                "if . then 1 elif . then 2 else 3 end",
                "(if . 1 (if . 2 3))",
            ),
            ("if 1,2 then 3,4 else 5 end", "(if (, 1 2) (, 3 4) 5)"),
            (
                "reduce .[] as $x (0; . + $x) | . * 2",
                "(| (reduce (each .) $x 0 (+ . $x)) (* . 2))",
            ),
            ("reduce 1 + 2 as $x (0; .)", "(reduce (+ 1 2) $x 0 .)"),
            (
                "foreach .[] as [$a, $b] (0; 1; 2)",
                "(foreach (each .) [$a $b] 0 1 2)",
            ),
            ("foreach .[] as $x (0; 1)", "(foreach (each .) $x 0 1)"),
            (". as $x | $x, 1", "(as . $x (, $x 1))"),
            ("1, . as $x | $x", "(, 1 (as . $x $x))"),
            (
                ".[0] + .[1] as $x | $x",
                "(as (+ (index . 0) (index . 1)) $x $x)",
            ),
            (
                ". as [$a] ?// {b: $a} ?// $a | $a",
                "(as . (?// [$a] {(\"b\" $a)} $a) $a)",
            ),
            (
                ". as {a: $a, $b, \"c\": $c, (\"d\"): $d, $e: [$f], if: $g} | 1",
                "(as . {(\"a\" $a) $b (\"c\" $c) ((\"d\") $d) ($e [$f]) (\"if\" $g)} 1)",
            ),
            (
                "label $out | 1, break $out",
                "(label $out (, 1 (break $out)))",
            ),
            ("1, label $x | 2, 3", "(, 1 (label $x (, 2 3)))"),
            ("def f: 1; f | g", "(defs (def f 1) (| f g))"),
            (
                "def f($a; b): $a; f(1; 2)",
                "(defs (def f ($a b) $a) (call f 1 2))",
            ),
            ("1, def f: 2; f", "(, 1 (defs (def f 2) f))"),
            (
                "def f: def g: 1; g; f",
                "(defs (def f (defs (def g 1) g)) f)",
            ),
            ("def f: 1; def g: 2;", "(library (def f 1) (def g 2))"),
            ("", "(library)"),
            ("# just a comment", "(library)"),
        ]);
        assert_eq!(
            first_error("try error(\"x\") + 1 catch ."),
            "syntax error, unexpected catch, expecting end of file"
        );
        assert_eq!(
            first_error("1 + def f: 2; f"),
            "syntax error, unexpected def"
        );
        assert_eq!(
            first_error("def f(): 1; 1"),
            "syntax error, unexpected ')', expecting IDENT or BINDING"
        );
    }

    #[test]
    fn terms() {
        check(&[
            ("true", "true"),
            ("false", "false"),
            ("null", "null"),
            ("true(1)", "(call true 1)"),
            ("a::b", "a::b"),
            ("a::b(1)", "(call a::b 1)"),
            ("$x", "$x"),
            ("$$$$x", "$$$$x"),
            ("$__loc__", "$__loc__"),
            ("$__loc__x", "$__loc__x"),
            ("@base64", "@base64"),
            ("@base64 \"x\\(.)\"", "(str @base64 \"x\" (interp .))"),
            ("\"a\\(1)b\"", "(str \"a\" (interp 1) \"b\")"),
            ("\"a\\nb\"", "(str \"a\" \"\\n\" \"b\")"),
            ("\"\"", "(str)"),
            ("[]", "(array)"),
            ("[1, 2]", "(array (, 1 2))"),
            ("{}", "(object)"),
            (
                "{a: 1 | 2, b, $c, \"d\", \"e\": 3, (.f): 4, $g: 5, $__loc__, if, @text \"h\": 6}",
                "(object (\"a\" (| 1 2)) b $c (shorthand \"d\") (\"e\" 3) (((index . \"f\")) 4) ($g 5) $__loc__ if ((str @text \"h\") 6))",
            ),
            ("{a: (1 as $x | $x)}", "(object (\"a\" (as 1 $x $x)))"),
            (
                "{a: reduce . as $x (0; 1)}",
                "(object (\"a\" (reduce . $x 0 1)))",
            ),
        ]);
        assert_eq!(first_error("{a: 1, 2}"), "syntax error, unexpected LITERAL");
        // object values are `DictExpr`s: `Expr`s joined by `|`, so `as` needs parentheses
        assert_eq!(
            first_error("{a: 1 as $x | $x}"),
            "syntax error, unexpected as, expecting '}'"
        );
        assert_eq!(
            first_error("$"),
            "syntax error, unexpected end of file, expecting '$'"
        );
        assert_eq!(
            first_error("@"),
            "syntax error, unexpected INVALID_CHARACTER, expecting end of file"
        );
    }

    #[test]
    fn modules_and_imports() {
        assert_eq!(
            sexpr(
                "module {a: 1}; import \"a\" as foo; import \"b\" as $d; include \"c\" {x: 1}; foo::f"
            ),
            "(module (object (\"a\" 1))) (import \"a\" foo) (import \"b\" $d) (include \"c\" (object (\"x\" 1))) foo::f"
        );
        let p = parse_program("import \"a\" as foo; .").unwrap();
        assert_eq!(p.imports[0].path, "a");
        assert_eq!(p.imports[0].kind, ImportKind::Code("foo".into()));
        let errors = parse_program("include \"\\(1)\"; .").unwrap_err();
        assert_eq!(errors[0].message, "Import path must be constant");
        assert_eq!(errors[0].loc, Loc::new(8, 14));
    }

    fn main_node(p: &Program) -> &Node {
        match &p.body {
            ProgramBody::Main(n) => n,
            ProgramBody::Library(_) => panic!("no main"),
        }
    }

    #[test]
    fn locations() {
        let p = parse_program("  f(1) | $x | $__loc__").unwrap();
        let n = main_node(&p);
        assert_eq!(n.loc, Loc::new(2, 22));
        let NodeKind::Pipe(a, rest) = &n.kind else {
            panic!()
        };
        let NodeKind::Call { name_loc, .. } = &a.kind else {
            panic!()
        };
        assert_eq!((a.loc, *name_loc), (Loc::new(2, 6), Loc::new(2, 3)));
        let NodeKind::Pipe(var, loc) = &rest.kind else {
            panic!()
        };
        assert_eq!(var.loc, Loc::new(9, 11));
        assert_eq!(loc.loc, Loc::new(14, 22));

        // parentheses don't widen a node's location
        let p = parse_program("(.a)").unwrap();
        assert_eq!(main_node(&p).loc, Loc::new(1, 3));

        // $__loc__ line numbers come from the locfile
        let src = "1 |\n\n  $__loc__";
        let lf = LocFile::new("<top-level>", src.as_bytes());
        let p = parse_program(src).unwrap();
        let NodeKind::Pipe(_, l) = &main_node(&p).kind else {
            panic!()
        };
        assert_eq!(lf.get_line(l.loc.start) + 1, 3);
    }

    #[test]
    fn error_messages_render_like_jq() {
        let src = "if . then 1";
        let errors = parse_program(src).unwrap_err();
        let lf = LocFile::new("<top-level>", src.as_bytes());
        let rendered: Vec<_> = errors.iter().map(|e| e.render(&lf)).collect();
        assert_eq!(
            rendered,
            [
                "jq: error: syntax error, unexpected end of file at <top-level>, line 1, column 11:\n    if . then 1\n              ^",
                "jq: error: Possibly unterminated 'if' statement at <top-level>, line 1, column 1:\n    if . then 1\n    ^^^^^^^^^^^",
            ]
        );
    }

    /// Flags number-literal keys and non-object metadata, like jq's constant checks.
    struct LiteralHooks(Vec<String>);

    impl ParseHooks for LiteralHooks {
        fn check_object_key(&mut self, key: &Node) -> Option<String> {
            self.0.push(key.to_sexpr());
            match &key.kind {
                NodeKind::Literal(Literal::Number(n)) => {
                    Some(format!("Cannot use number ({n}) as object key"))
                }
                _ => None,
            }
        }
        fn check_metadata(&mut self, meta: &Node) -> Option<String> {
            match &meta.kind {
                NodeKind::Object(_) => None,
                _ => Some("Module metadata must be an object".into()),
            }
        }
    }

    fn messages(src: &str, hooks: &mut dyn ParseHooks) -> Vec<String> {
        parse(src.as_bytes(), hooks)
            .unwrap_err()
            .into_iter()
            .map(|e| e.message)
            .collect()
    }

    #[test]
    fn hooks_run_in_jq_order() {
        let mut h = LiteralHooks(Vec::new());
        // the key check runs when the pair is reduced, before the later syntax error
        assert_eq!(
            messages("[{(0):1} 2]", &mut h),
            [
                "Cannot use number (0) as object key",
                "syntax error, unexpected LITERAL, expecting '|' or ',' or ']'"
            ]
        );
        assert_eq!(
            messages("(1 2), {(0):1}", &mut h),
            [
                "syntax error, unexpected LITERAL, expecting '|' or ',' or ')'",
                "Cannot use number (0) as object key"
            ]
        );
        // inner pairs are reduced first
        assert_eq!(
            messages("{(0): {(1): 2}}", &mut h),
            [
                "Cannot use number (1) as object key",
                "Cannot use number (0) as object key"
            ]
        );
        // error-recovery values reach the hooks: `if 1 then 2` recovers as its condition
        h.0.clear();
        assert_eq!(
            messages("{(if 1 then 2):3}", &mut h),
            [
                "syntax error, unexpected ')'",
                "Possibly unterminated 'if' statement",
                "Cannot use number (1) as object key"
            ]
        );
        assert_eq!(h.0, ["1"]);
        assert_eq!(
            messages("module []; .", &mut h),
            ["Module metadata must be an object"]
        );
        let p = parse(b"include \"a\" {}; .", &mut h).unwrap();
        assert_eq!(p.imports.len(), 1);
    }

    #[test]
    fn deep_left_chains_do_not_overflow() {
        // jq accepts these (the parser stack stays shallow); dropping the AST must not
        // recurse once per term.
        let plus = format!("1{}", "+1".repeat(200_000));
        assert!(parse_program(&plus).is_ok());
        let comma = format!("[1{}]", ",1".repeat(200_000));
        assert!(parse_program(&comma).is_ok());
        let fields = ".a".repeat(200_000);
        assert!(parse_program(&fields).is_ok());
        let opt = format!(".{}", "?".repeat(200_000));
        assert!(parse_program(&opt).is_ok());
    }

    #[test]
    fn libraries() {
        let lib = parse_library(b"def f: 1; def g: f;", &mut NoHooks).unwrap();
        assert!(matches!(&lib.body, ProgramBody::Library(defs) if defs.len() == 2));
        assert!(parse_library(b"", &mut NoHooks).is_ok());
        let src = b"def f: 1; 1";
        let errors = parse_library(src, &mut NoHooks).unwrap_err();
        let lf = LocFile::new("m.jq", src);
        assert_eq!(
            errors[0].render(&lf),
            "jq: error: jq: error: library should only have function definitions, not a main expression"
        );
        // syntax errors are reported as by `parse`, located in the module's file
        let src = b"def f: 1; .a b";
        let errors = parse_library(src, &mut NoHooks).unwrap_err();
        let lf = LocFile::new("lib/s.jq", src);
        assert_eq!(
            errors[0].render(&lf),
            "jq: error: syntax error, unexpected IDENT, expecting end of file at lib/s.jq, line 1, column 14:\n    def f: 1; .a b\n                 ^"
        );
    }

    #[test]
    fn stack_limit_is_bisons() {
        // YYMAXDEPTH: the 10000th state push fails
        let ok = format!("{}{}", "[".repeat(9995), "]".repeat(9995));
        assert!(parse_program(&ok).is_ok());
        let deep = format!("{}{}", "[".repeat(9996), "]".repeat(9996));
        let errors = parse_program(&deep).unwrap_err();
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].message, "memory exhausted");
        assert_eq!(errors[0].loc, Loc::new(9996, 9997));
    }
}
